In [1]:
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv('titanic_data.csv')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
df['deck'].unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F'], dtype=object)

In [4]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            176
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     889 non-null    int64  
 1   pclass       889 non-null    int64  
 2   sex          889 non-null    object 
 3   age          713 non-null    float64
 4   sibsp        889 non-null    int64  
 5   parch        889 non-null    int64  
 6   fare         889 non-null    float64
 7   embarked     887 non-null    object 
 8   class        889 non-null    object 
 9   who          889 non-null    object 
 10  adult_male   889 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  887 non-null    object 
 13  alive        889 non-null    object 
 14  alone        889 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.2+ KB


In [6]:
df.drop(['adult_male','deck','alive'],axis=1,  inplace=True)

In [7]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
884         0       2    male  27.0      0      0  13.0000        S  Second   
885         1       1  female  19.0      0      0  30.0000        S   First   
886         0       3  female   NaN      1      2  23.4500        S   Third   
887         1       1    male  26.0      0      0  30.0000        C   First   
888         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  embark_town  alone  
0      man  Southampton  False  
1    woman    Cherbourg  False  
2    woman  Southampton   True  
3    woman  Southampton  False  
4      man  Southampton   True  
..     ...          ...    ...  
884    man  Southampton   True  
885  woman  Southampton   True  
886  woman  Southampton  False  
887    man    Cherbourg   True  
888    man   Queenstown   True  

[889 rows x 12 columns]

In [8]:
df['age']=df['age'].fillna(df['age'].mean())

In [9]:
df.dropna(subset=['embarked'], inplace=True)

In [10]:
df.dropna(subset=['embark_town'], inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 887 entries, 0 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     887 non-null    int64  
 1   pclass       887 non-null    int64  
 2   sex          887 non-null    object 
 3   age          887 non-null    float64
 4   sibsp        887 non-null    int64  
 5   parch        887 non-null    int64  
 6   fare         887 non-null    float64
 7   embarked     887 non-null    object 
 8   class        887 non-null    object 
 9   who          887 non-null    object 
 10  embark_town  887 non-null    object 
 11  alone        887 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(5)
memory usage: 84.0+ KB


In [12]:
df

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
884         0       2    male  27.000000      0      0  13.0000        S   
885         1       1  female  19.000000      0      0  30.0000        S   
886         0       3  female  29.698696      1      2  23.4500        S   
887         1       1    male  26.000000      0      0  30.0000        C   
888         0       3    male  32.000000      0      0   7.7500        Q   

      class    who  embark_town  alone  
0     Third    man  Southampton  False  
1     First  woman    Cherbourg  False  
2     Third  woman  Southampton   True  
3     First  woman  Southampton  False  
4     Third    man  Southampton   True  
..      ...    ...          ...    ...  
884  Second    man  Southampton   True  
885   First  woman  Southampton   True  
886   Third  woman  Southampton  False  
887   First    man    Cherbourg   True  
888   Third    man   Queenstown   True  

[887 rows x 12 columns]

In [13]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

In [14]:
encoder = OrdinalEncoder()
encoder.fit(df[['class']])
df['class'] = encoder.transform(df[['class']])

In [15]:
df

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
884         0       2    male  27.000000      0      0  13.0000        S   
885         1       1  female  19.000000      0      0  30.0000        S   
886         0       3  female  29.698696      1      2  23.4500        S   
887         1       1    male  26.000000      0      0  30.0000        C   
888         0       3    male  32.000000      0      0   7.7500        Q   

     class    who  embark_town  alone  
0      2.0    man  Southampton  False  
1      0.0  woman    Cherbourg  False  
2      2.0  woman  Southampton   True  
3      0.0  woman  Southampton  False  
4      2.0    man  Southampton   True  
..     ...    ...          ...    ...  
884    1.0    man  Southampton   True  
885    0.0  woman  Southampton   True  
886    2.0  woman  Southampton  False  
887    0.0    man    Cherbourg   True  
888    2.0    man   Queenstown   True  

[887 rows x 12 columns]

In [16]:
X=df.drop('survived', axis=1)

In [17]:
y=df['survived']

In [18]:
X

pclass     sex        age  sibsp  parch     fare embarked  class    who  \
0         3    male  22.000000      1      0   7.2500        S    2.0    man   
1         1  female  38.000000      1      0  71.2833        C    0.0  woman   
2         3  female  26.000000      0      0   7.9250        S    2.0  woman   
3         1  female  35.000000      1      0  53.1000        S    0.0  woman   
4         3    male  35.000000      0      0   8.0500        S    2.0    man   
..      ...     ...        ...    ...    ...      ...      ...    ...    ...   
884       2    male  27.000000      0      0  13.0000        S    1.0    man   
885       1  female  19.000000      0      0  30.0000        S    0.0  woman   
886       3  female  29.698696      1      2  23.4500        S    2.0  woman   
887       1    male  26.000000      0      0  30.0000        C    0.0    man   
888       3    male  32.000000      0      0   7.7500        Q    2.0    man   

     embark_town  alone  
0    Southampton  False  
1      Cherbourg  False  
2    Southampton   True  
3    Southampton  False  
4    Southampton   True  
..           ...    ...  
884  Southampton   True  
885  Southampton   True  
886  Southampton  False  
887    Cherbourg   True  
888   Queenstown   True  

[887 rows x 11 columns]

In [19]:
ct = ColumnTransformer([('ll', OneHotEncoder(drop='first'), [1,6,8,9,10])], remainder='passthrough')
X=ct.fit_transform(X)

In [20]:
X

array([[ 1.    ,  0.    ,  1.    , ...,  0.    ,  7.25  ,  2.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    , 71.2833,  0.    ],
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  7.925 ,  2.    ],
       ...,
       [ 0.    ,  0.    ,  1.    , ...,  2.    , 23.45  ,  2.    ],
       [ 1.    ,  0.    ,  0.    , ...,  0.    , 30.    ,  0.    ],
       [ 1.    ,  1.    ,  0.    , ...,  0.    ,  7.75  ,  2.    ]])

In [21]:
# cat_values=pd.get_dummies(df[['sex','embark_town','who', 'embarked']], dtype=int)

In [22]:
# df.drop(['sex', 'embarked', 'who', 'embark_town'],axis=1, inplace=True)

In [23]:
# df=pd.concat([df,cat_values], axis=1)

In [24]:
df

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
884         0       2    male  27.000000      0      0  13.0000        S   
885         1       1  female  19.000000      0      0  30.0000        S   
886         0       3  female  29.698696      1      2  23.4500        S   
887         1       1    male  26.000000      0      0  30.0000        C   
888         0       3    male  32.000000      0      0   7.7500        Q   

     class    who  embark_town  alone  
0      2.0    man  Southampton  False  
1      0.0  woman    Cherbourg  False  
2      2.0  woman  Southampton   True  
3      0.0  woman  Southampton  False  
4      2.0    man  Southampton   True  
..     ...    ...          ...    ...  
884    1.0    man  Southampton   True  
885    0.0  woman  Southampton   True  
886    2.0  woman  Southampton  False  
887    0.0    man    Cherbourg   True  
888    2.0    man   Queenstown   True  

[887 rows x 12 columns]

In [25]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [26]:
X

array([[ 0.73661978, -0.30612329,  0.61601236, ..., -0.4749808 ,
        -0.50091232,  0.82677342],
       [-1.35755247, -0.30612329, -1.62334405, ..., -0.4749808 ,
         0.78716995, -1.56978874],
       [-1.35755247, -0.30612329,  0.61601236, ..., -0.4749808 ,
        -0.48733414,  0.82677342],
       ...,
       [-1.35755247, -0.30612329,  0.61601236, ...,  2.00330136,
        -0.17503605,  0.82677342],
       [ 0.73661978, -0.30612329, -1.62334405, ..., -0.4749808 ,
        -0.04327744, -1.56978874],
       [ 0.73661978,  3.26665772, -1.62334405, ..., -0.4749808 ,
        -0.49085441,  0.82677342]])

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(X_train, y_train)

LogisticRegression()

In [29]:
pred_lr=LR.predict(X_test)

In [30]:
from sklearn.metrics import classification_report

In [31]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       130
           1       0.79      0.73      0.76        92

    accuracy                           0.81       222
   macro avg       0.80      0.79      0.80       222
weighted avg       0.81      0.81      0.81       222



In [32]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       130
           1       0.79      0.73      0.76        92

    accuracy                           0.81       222
   macro avg       0.80      0.79      0.80       222
weighted avg       0.81      0.81      0.81       222



In [33]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       130
           1       0.79      0.73      0.76        92

    accuracy                           0.81       222
   macro avg       0.80      0.79      0.80       222
weighted avg       0.81      0.81      0.81       222



In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(X_train, y_train)

KNeighborsClassifier()

In [36]:
pred_kn=kn.predict(X_test)

In [37]:
print(classification_report(y_test, pred_kn))

              precision    recall  f1-score   support

           0       0.79      0.85      0.81       130
           1       0.76      0.67      0.71        92

    accuracy                           0.77       222
   macro avg       0.77      0.76      0.76       222
weighted avg       0.77      0.77      0.77       222



In [38]:
print(classification_report(y_test, pred_kn))

              precision    recall  f1-score   support

           0       0.79      0.85      0.81       130
           1       0.76      0.67      0.71        92

    accuracy                           0.77       222
   macro avg       0.77      0.76      0.76       222
weighted avg       0.77      0.77      0.77       222



In [39]:
from sklearn.svm import SVC

In [40]:
sv=SVC(kernel='rbf')
sv.fit(X_train, y_train)

SVC()

In [41]:
pred_sv=sv.predict(X_test)

In [42]:
print(classification_report(y_test, pred_sv))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       130
           1       0.80      0.66      0.73        92

    accuracy                           0.79       222
   macro avg       0.80      0.77      0.78       222
weighted avg       0.79      0.79      0.79       222



In [43]:
print(classification_report(y_test, pred_sv))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       130
           1       0.80      0.66      0.73        92

    accuracy                           0.79       222
   macro avg       0.80      0.77      0.78       222
weighted avg       0.79      0.79      0.79       222



In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
rf=RandomForestClassifier(n_estimators=1000, max_depth=3)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, n_estimators=1000)

In [46]:
pred_rf=rf.predict(X_test)

In [47]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.76      0.88      0.82       130
           1       0.79      0.61      0.69        92

    accuracy                           0.77       222
   macro avg       0.78      0.75      0.75       222
weighted avg       0.77      0.77      0.76       222



In [48]:
pipe = Pipeline([('scaler', StandardScaler()), ('lr',LogisticRegression())])

In [49]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('lr', LogisticRegression())])

In [50]:
pipe.predict(X_test)

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0], dtype=int64)

In [51]:
pipe.score(X_test, y_test)

0.8063063063063063