In [3]:
import numpy as np
import pandas as pd

In [6]:
arr1=np.array([[2,5]])
arr2=np.array([[4,1]])
arr1 + arr2

array([[6, 6]])

In [41]:
arr1 + arr2

array([[ 6,  6],
       [14, 12]])

In [48]:
arr1 * arr2

array([[ 8,  5],
       [48, 27]])

In [43]:
arr1 - arr2

array([[-2,  4],
       [-2, -6]])

In [13]:
gf=np.random.randint(1, 10, (2,3))

In [102]:
gf.shape

(2, 3)

In [85]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
Age=pd.Series([10, 20, 30, 40] ,index=['ali', 'sina', 'fatemeh', 'negar'])
Age

ali        10
sina       20
fatemeh    30
negar      40
dtype: int64

In [87]:
Age['negar']

np.int64(40)

In [68]:
Age.values

array([10, 20, 30, 40])

In [88]:
Age.ali

np.int64(10)

In [91]:
Age>10

ali        False
sina        True
fatemeh     True
negar       True
dtype: bool

In [16]:
Age[[False, False, True, True]]

fatemeh    30
negar      40
dtype: int64

In [23]:
Age[(Age > 10) & (Age<30)]


sina       20
fatemeh    30
negar      40
dtype: int64

In [9]:
df=pd.DataFrame([[160,68,28], [174, 77, 32]], index=['ali', 'sina'], columns=['height', 'weight', 'age'])
df

height  weight  age
ali      160      68   28
sina     174      77   32

In [45]:
df=pd.read_excel(r'C:\Users\mahdi\Downloads\Telegram Desktop\updater (2) - Copy.xlsx')
df

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...     NaN       0   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6       0   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path      name  
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay  
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...      meli  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    sizpay

In [5]:
df.head(2)

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...  2.35.6       0   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path      name  
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay

In [6]:
df.tail(1)

edit page url version  status  \
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path    name  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  sizpay

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   edit page url  4 non-null      object
 1   version        4 non-null      object
 2   status         4 non-null      int64 
 3   file path      4 non-null      object
 4   name           4 non-null      object
dtypes: int64(1), object(4)
memory usage: 292.0+ bytes


In [11]:
df.describe()

status
count  4.00000
mean   0.50000
std    0.57735
min    0.00000
25%    0.00000
50%    0.50000
75%    1.00000
max    1.00000

In [21]:
df[(df['status']>df['status'].mean())]

edit page url version  status  \
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path    name  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...   idpay  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  sizpay

In [96]:
df.iloc[-3:,3:]

file path    name
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...   idpay
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    meli
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  sizpay

In [99]:
df.loc[0:1, 'status':]

status                                          file path      name
0       0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal
1       1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay

In [46]:
df.fillna(2.33)

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...    2.33       0   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6       0   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path      name  
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay  
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...      meli  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    sizpay

In [47]:
df.dropna()

edit page url version  status  \
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6       0   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path    name  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...   idpay  
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    meli  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  sizpay

In [114]:
df.drop(1, axis=0)

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...     1.0      12   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   

                                           file path          name  \
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...        sister   
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  my future gf   
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...        sister   

   count_of_cars       sibling  
0              3        sister  
2              3  my future gf  
3              4        sister

In [86]:
# df.fillna(df['status'].mean())
df=df.fillna(df[df['status']==1]['status'].mean()) 

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...     1.0       0   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6       0   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path      name  
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay  
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...      meli  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    sizpay

In [90]:
df.replace({'status':{1:'kos', 0:'kir'}})

edit page url version status  \
0  https://www.zhaket.com/dashboard/products/edit...     1.0    kir   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6    kos   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6    kir   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6    kos   

                                           file path      name  
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay  
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...      meli  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    sizpay

In [91]:
df.replace({'name':{'meli':'kos'}})

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...     1.0       0   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6       0   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path      name  
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay  
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...       kos  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    sizpay

In [93]:
df['status'].mean()

np.float64(0.5)

In [102]:
df['count_of_cars']= df['status'] +3
df

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...     1.0       0   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6       0   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6       1   

                                           file path      name  count_of_cars  
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  zarinpal              3  
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...     idpay              4  
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...      meli              3  
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...    sizpay              4

In [105]:
df['status']= 2*6
df['status']

0    12
1    12
2    12
3    12
Name: status, dtype: int64

In [108]:
def categorizer(x):
    if x == 'meli':
        return 'my future gf'
    elif x == 'idpay':
        return 'brother'
    else:
        return 'sister'

df['name']=df['name'].apply(categorizer)
df

edit page url version  status  \
0  https://www.zhaket.com/dashboard/products/edit...     1.0      12   
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   

                                           file path          name  \
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...        sister   
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...       brother   
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  my future gf   
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...        sister   

   count_of_cars       sibling  
0              3        sister  
1              4       brother  
2              3  my future gf  
3              4        sister

In [113]:
df.sort_values(by=['count_of_cars', 'version'], ascending=False)

edit page url version  status  \
1  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   
3  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   
2  https://www.zhaket.com/dashboard/products/edit...  2.35.6      12   
0  https://www.zhaket.com/dashboard/products/edit...     1.0      12   

                                           file path          name  \
1  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...       brother   
3  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...        sister   
2  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...  my future gf   
0  C:\Users\mahdi\Downloads\Telegram Desktop\zhak...        sister   

   count_of_cars       sibling  
1              4       brother  
3              4        sister  
2              3  my future gf  
0              3        sister