In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [4]:
df=pd.read_csv('cardio_train1.csv')
df.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0   
1   1  20228       1     156    85.0    140     90            3     1      0   
2   2  18857       1     165    64.0    130     70            3     1      0   
3   3  17623       2     169    82.0    150    100            1     1      0   
4   4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       0       1  
3     0       1       1  
4     0       0       0

In [55]:
X=df.iloc[:, 1:-1]
y=df.iloc[:, -1]

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [10]:
X=sc.fit_transform(X)
X

array([[-0.43606151,  1.36405487,  0.44345206, ..., -0.31087913,
        -0.23838436,  0.49416711],
       [ 0.30768633, -0.73310834, -1.01816804, ..., -0.31087913,
        -0.23838436,  0.49416711],
       [-0.24799666, -0.73310834,  0.07804703, ..., -0.31087913,
        -0.23838436, -2.02360695],
       ...,
       [-0.16328642,  1.36405487,  2.27047718, ..., -0.31087913,
         4.19490608, -2.02360695],
       [ 1.20058905, -0.73310834, -0.16555632, ..., -0.31087913,
        -0.23838436, -2.02360695],
       [ 0.43414373, -0.73310834,  0.68705541, ..., -0.31087913,
        -0.23838436,  0.49416711]])

In [57]:
y=pd.get_dummies(y, dtype=int)

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33123)

In [70]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(11, activation='relu', input_shape=(11,)),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

In [71]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.CategoricalCrossentropy(), metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [73]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), batch_size=100)

Epoch 1/50
525/525 [==============================] - 3s 6ms/step - loss: 3.5678 - categorical_accuracy: 0.5566 - val_loss: 9.8207 - val_categorical_accuracy: 0.5055
Epoch 2/50
525/525 [==============================] - 4s 7ms/step - loss: 5.9624 - categorical_accuracy: 0.5396 - val_loss: 0.9440 - val_categorical_accuracy: 0.6758
Epoch 3/50
525/525 [==============================] - 3s 5ms/step - loss: 3.0795 - categorical_accuracy: 0.5742 - val_loss: 3.4655 - val_categorical_accuracy: 0.5086
Epoch 4/50
525/525 [==============================] - 3s 5ms/step - loss: 3.0489 - categorical_accuracy: 0.5660 - val_loss: 3.4897 - val_categorical_accuracy: 0.5074
Epoch 5/50
525/525 [==============================] - 3s 6ms/step - loss: 3.1209 - categorical_accuracy: 0.5740 - val_loss: 0.9279 - val_categorical_accuracy: 0.6890
Epoch 6/50
525/525 [==============================] - 3s 6ms/step - loss: 2.3947 - categorical_accuracy: 0.5827 - val_loss: 1.6351 - val_categorical_accuracy: 0.5858
Epoc

In [74]:
from sklearn.metrics import classification_report

In [80]:
np.argmax(model.predict(X_test)[3])

547/547 [==============================] - 1s 3ms/step


0

In [84]:
np.array(y_test)

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [0, 1],
       [0, 1],
       [0, 1]])

In [81]:
y_pred=np.argmax(model.predict(X_test), axis=1)
y_pred

547/547 [==============================] - 1s 2ms/step


array([1, 0, 1, ..., 1, 1, 0], dtype=int64)